[pytest]
addopts = 
        --strict-markers
        --alluredir allure-results
        --clean-alluredir
pythonpath = .
markers =
        flaky: mark a test as flaky, it will be rerun on failure
        welcome_reset(step): Reset welcome flow and navigate to given step
        smoke: mark a test as smoke, it will be run as smoke test       
        regression: mark a test as regression, it will be run as regression test
        positive: mark a test as positive, it will be run as positive test
        negative: mark a test as negative, it will be run as negative test